version: '3.7'
services:
  proxy:
    container_name: reverseProxy
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert/:/etc/nginx/ssl
    restart: always
networks:
  default:
    external:
     name: oasip_nw