version: '3.3'
services:
  oasip_DB:
    container_name: oasip_DB
    volumes:
      - ./scriptDB/oasip_v2_script.sql:/docker-entrypoint-initdb.d/oasip.sql
    environment:
      - MYSQL_USER=oasip_user
      - MYSQL_DATABASE=oasip
      - MYSQL_PASSWORD=kmutt@631305.78
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Bangkok
    ports:
      # - '3307:3306'
      - '3306:3306'
    image: mysql:8
    restart: always
    command: --character_set_results=utf8mb4 --character_set_connection=utf8mb4 --character_set_client=utf8mb4 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=+07:00
networks:
  default:
    external:
      name: oasip_nw