version: '3.7'
services:
  backEnd:
    container_name: backEnd
    image: oasip_back_img
    build: ./
    environment:
      - spring.datasource.url=jdbc:mysql://oasipDB:3306/oasip
    restart: always
    ports:
      - '8080:8080'
networks:
  default:
    external:
      name: oasip_nw