version: '3.7'
services:
  oasip_Back_End:
    container_name: oasip_Back_End
    image: oasip_back_img
    build: ./
    environment:
      - spring.datasource.url=jdbc:mysql://oasip_DB:3306/oasip
    restart: always
networks:
  default:
    external:
      name: oasip_nw