version: '3.7'
services:
  frontEnd:
    container_name: frontEnd
    image: oasip_front_img
    build: ./
    ports : 
      - '3000:3000'
    restart: always
networks:
  default:
    external:
      name: oasip_nw
