version: '3.3'
services:
  oasip_Front_End:
    container_name: oasip_Front_End
    image: oasip_front_img
    build: ./
    volumes:
      - ./cert/private.key:/etc/nginx/ssl/www-ip21ssa.key
      - ./cert/www-ip21ssa.crt:/etc/nginx/ssl/www-ip21ssa.crt
    ports : 
      - '80:80'
    restart: always
networks:
  default:
    external:
      name: oasip_nw
