-- MySQL Script generated by MySQL Workbench
-- Tue Aug  9 22:28:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oasip
-- -----------------------------------------------------eventcategoryeventcategory

-- -----------------------------------------------------
-- Schema oasip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oasip` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema oasip
-- -----------------------------------------------------
USE `oasip` ;

-- -----------------------------------------------------
-- Table `oasip`.`eventcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oasip`.`eventcategory` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(550) NULL,
  `duration` INT NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oasip`.`eventbooking`
-- -----------------------------------------------------
-- drop table eventbooking ;
-- drop table eventcategory;

CREATE TABLE IF NOT EXISTS `oasip`.`eventbooking` (
  `booking_id` INT NOT NULL auto_increment,
  `booking_name` VARCHAR(150) NOT NULL,
  `booking_email` VARCHAR(150) NOT NULL,
  `start_time` DATETIME NOT NULL,
  `booking_duration` INT NOT NULL,
  `event_note` VARCHAR(550) NULL,
  `update_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `category` INT NOT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `fk_eventbooking_eventcategory_idx` (`category` ASC) VISIBLE,
  CONSTRAINT `fk_eventbooking_eventcategory`
    FOREIGN KEY (`category`)
    REFERENCES `oasip`.`eventcategory` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into `eventcategory` (`category_id`,`category_name`,`description`,`duration`) values 
(1, 'Project Management Clinic','ตารางนัดหมายนี้ใช้สำหรับนัดหมาย project management clinic ในวิชา INT221 integrated project I ให้นักศึกษาเตรียมเอกสารที่เกี่ยวข้องเพื่อแสดง EventBooking ระหว่างขอคำปรึกษา', 30 ),
(2,'DevOps/Infra Clinic','Use this event category for DevOps/Infra clinic.',20),
(3,'Database Clinic','ตารางนัดหมายนี้ใช้สำหรับนัดหมาย database clinic ในวิชา INT221 integrated project I',15),
(4,'Client-side Clinic','ตารางนัดหมายนี้ใช้สำหรับนัดหมาย client-side clinic ในวิชา INT221 integrated project',30),
(5,'Server-side Clinic',' ',30);

insert into `eventbooking` (`booking_id`,`booking_name`,`booking_email`,`start_time`,`booking_duration`,`event_note`,`update_date`,`category`) values 
(1,'Somchai Jaidee (OR-7)','somchai.jai@mail.kmutt.ac.th','2022-05-23 13:00',30,' ',now(),2),
(2,'Somsri Rakdee (SJ-3)','somsri.rak@mail.kmutt.ac.th','2022-04-27 09:30',30,' ขอปรึกษาเรื่องเพื่อนไม่ช่วยงาน ',now(),1),
(3,'สมเกียรติ ขยันเรียน กลุ่ม TT-4','somkiat.kay@kmutt.ac.th','2022-05-23 16:30',15,' ',now(),3);

