# This is a basic workflow to help you get started with Actions

name: Front-CI

# Controls when the workflow will run
on: [push]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Create Docker network
        run: sudo docker network create oasip_nw
      - name: Build Docker
        run: |
          cd Front-end/OASIP-Client
          sudo docker-compose down
          sudo docker-compose up -d --build
    
